import './index.html';
import './index.scss';
import './js/swiper';
import './js/swiper2';
import './js/button--button';
import './js/modal-call';
import './js/modal-feedback';
import './js/text';
import './js/buty';